= System Context

[NOTE]
This diagram shows the systems that are communicating and interacting within the scope of the Enterprise Guardian Platform. It shows the different systems and how they interact with each other. The diagram should be updated when new systems are added or removed from the platform.

The example below gives a view on the different types of components

// tag::architect[]
[plantuml,target=images/level1,format=svg]
----

@startuml
!define C4_CONTEXT
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_TOP_DOWN()

title Enterprise Guardian System Context Diagram

Person_Ext(user, "User", "Carbon Data submitter")
Person_Ext(Registery, "Registery", "Registery Authority")
Person_Ext(sysadmin, "Sysadmin", "System admin from HGA")

System_Ext(workflow, "Enterprise Guardian Service", "Workflow Engine and Orchastrators, to manage and validate polices, schemes, data, and authuntication")
System(guardiansystem, "Enterprise Guardian Blockchain", "Tracks agricultural produce through blockchain technology using Hedera Consensus Service")
System_Ext(hcs, "Hedera Consensus Service", "Blockchain infrastructure for immutable event logging")

Rel(user, workflow, "Submit data")
Rel(Registery, workflow, "Create policies, accounts, schemes")
Rel(sysadmin, workflow, "Manage BE and tenants")
Rel(workflow, guardiansystem, "Logs data on HCS")
Rel(guardiansystem, hcs, "Logs events securely")
@enduml
----

== SysAdmin User
[NOTE]
The SysAdmin is responsible for maintaining all system components, creating and managing tenants, and inviting/creating registry accounts within the Guardian system. This role is typically assigned to HGA staff.

== User
[NOTE]
The User represents the end entity or organization that utilizes the Guardian system to submit their carbon data. This is the primary user of the system.

== Registry Authority
[NOTE]
The Registry Authority is responsible for creating, designing, and providing policies, schemes, accounts, and users. They are the primary designer of all policies within the workflow.

