=== Container View

The Entriprise Guardian System  is composed of six key containers that work together
to enable secure and transparent data registery on the Hedera Consensus Service (HCS).

[plantuml, target=images/level2, format=svg]
----
@startuml
!define C4_CONTAINER
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Enterprise Guardian System - Container Diagram

LAYOUT_TOP_DOWN()

Person_Ext(saas, "Enterprise Guardian Service", "External UI for system users")
System_Boundary(traceability, "Enterprise Guardian System") {
    Container(api_gateway, "API Gateway", "NestJS", "Handles all incoming requests and routes events")
    Container(Coreorc, "Orchastration Service", "", "Orchastration starter services for Policy, Scheme and transactions runtime.")
    Container(storage, "Storage Service", "Centralized DB Storage", "Stores and log all system interactions. Store and retrieves event data")
    Container(authsrv, "Auth Service", "", "Securely manages DID, cryptographic keys, permissions, and secrets")
    Container(workflowsrv, "Workflow Service", "Camunda Workflow Engine", "Excute Workflow as per predefined Polices based on BPMN")
    Container(workersrv, "Data Workers Services", "IPFS and DLT data managment workrs", "Excute data operations from and to IPFS and DLT.")
}

System_Ext(hcs, "Hedera Consensus Service", "Blockchain infrastructure for immutable event logging")

Rel(saas, api_gateway, "Sends API calls")
Rel(storage, workersrv, "Provides content references")

Rel(api_gateway, Coreorc, "Data submited")
Rel(Coreorc, workflowsrv, "Data submited")
Rel(workflowsrv, api_gateway, "Fetch message broker data")
Rel(workflowsrv, workersrv, "initiate data storage operations")


Rel(Coreorc, api_gateway, "Place data in message broker")

Rel(workersrv, storage, "Stores event data")
Rel(storage, hcs, "Publishes event hashes")

Rel(api_gateway, authsrv, "Validate Tokens and Crypto keys")
Rel(authsrv, api_gateway, "Provides Tokens and Crypto keys")

@enduml

----

=== Description of Modules and Components

==== Web Application

[NOTE]
Describe the design choices made for the web application. Framework (e.g. React, Angular) and other technical decisions. The features of the application are described elsewhere.

==== API Gateway

[NOTE]
Describe how the Web App interacts with the gateway, what the security or trust parameters are and other design choices.

==== Other components

[NOTE]
Describe why the components are required (e.g. Hexagonal architecture mandates separation of function and persistence) and what their main function is.
// end::developer[]
